<?php

namespace App\AI;

abstract class AIConfig
{
    //VISION
    protected string $visionModel = 'qwen3-vl:4b';
    protected string $visionPrompt = <<<EOT
You are an expert image analyst. Analyze the attached image thoroughly.
Include:
- OCR text (all visible text)
- Objects, logos, or handwritten notes
- Layout and context
- Any other visual clues

Do not summarize, categorize, or suggest actions. Respond **only with detailed observations**.
EOT;

    //TEXT
    protected string $textModel = 'llama3.1:latest';
    protected string $textPrompt;



    protected function getVisionModel(): string
    {
        return $this->visionModel;
    }

    protected function getVisionPrompt(): string
    {
        return $this->visionPrompt;
    }

    protected function getTextModel(): string
    {
        return $this->textModel;
    }

    protected function setTextPrompt($categoryContext, $visionData): string
    {

        $this->textPrompt = <<<EOT
You are SmartSorter AI, an expert archivist and personal assistant.
You will receive an image description generated by another AI.

Your task is to produce **STRICT JSON ONLY**.
No explanations. No markdown. No extra text.

### AVAILABLE CATEGORIES:
{$categoryContext}
- ID 0: "Uncategorized" (Use only if nothing fits)

### IMAGE DESCRIPTION:
{$visionData}

### TASKS:
1. Analyze the image description carefully.
2. Choose the **single best Category ID**.
3. Give a one-sentence reason.
4. Suggest the next best action.

### RESPONSE FORMAT (EXACT JSON):
{
  "category_id": 0,
  "confidence_score": 0,
  "summary": "",
  "reasoning": "",
  "extracted_data": {
    "date": null,
    "amount": null,
    "sender": null
  },
  "suggested_action": {
    "type": "archive",
    "label": "",
    "detail": ""
  }
}
EOT;
        return $this->textPrompt;
    }

    protected function getTextPrompt(): ?string
    {
        return $this->textPrompt;
    }

    // protected function setTextCategories($categories)
    // {
    //     $this->textCategories = $categories;
    // }

    // protected function getTextCategories(): ?string
    // {
    //     return $this->textCategories;
    // }
}
